name: flowblade-otel-lgtm

services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.13.0
    # 4000 is for the web ui
    ports: ['4000:3000', '4317:4317', '4318:4318', '4040:4040', '9090:9090']
    networks:
      - flowblade-net

networks:
  flowblade-net:
    driver: bridge
    enable_ipv6: false
